#pragma once
#include <cstdint>

struct DataMessage {
  uint32_t type;                  // must be 1
  uint32_t sender;                // sender's id
  uint32_t msg_id;                // id of the message generated by sender
  uint32_t data;                  // dummy integer
};

struct AckMessage {
  uint32_t type;                  // must be 2
  uint32_t sender;                // sender of DataMessage
  uint32_t msg_id;                // id of DataMessage generated by sender
  uint32_t proposed_seq;          // proposed sequence number
  uint32_t proposer;              // process id of proposer
};

struct SeqMessage {
  uint32_t type;                  // must be 3
  uint32_t sender;                // sender of DataMessage
  uint32_t msg_id;                // id of DataMessage generated by sender
  uint32_t final_seq;             // final sequence number selected by sender
  uint32_t final_seq_proposer;    // process id of the proposer who proposed 
                                  // final_seq
};